# Generated by Django 3.2.2 on 2024-03-30 13:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='id на потрeбител')),
                ('user_name', models.CharField(default='', max_length=50, null=True, verbose_name='име на потрeбител')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Подадена'), (2, 'Приета'), (3, 'Работи се'), (4, 'Затворена')], default=1)),
                ('message', models.TextField(blank=True, default='', verbose_name='действие')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='дата и час')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50, null=True, verbose_name='име на потрeбител')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Подадена'), (2, 'Приета'), (3, 'Работи се'), (4, 'Затворена')], default=1)),
                ('message', models.TextField(blank=True, default='', verbose_name='действие')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='дата и час')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='id на потрeбител')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
    ]
