# Generated by Django 3.2.2 on 2024-03-30 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_name',
        ),
        migrations.AddField(
            model_name='log',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_request_id', to='main.request', verbose_name='id на заявка'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user_id', to=settings.AUTH_USER_MODEL, verbose_name='id на потрeбител'),
        ),
    ]
