# Generated by Django 3.2.25 on 2024-03-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20240330_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(blank=True, default='', max_length=25, verbose_name='Кратко име')),
                ('name_full', models.CharField(blank=True, default='', max_length=25, verbose_name='Пълно име')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user_id', to=settings.AUTH_USER_MODEL, verbose_name='id на потрeбител')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенти',
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user_id', to='main.clients', verbose_name='id на потрeбител'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_user_id', to='main.clients', verbose_name='id на потрeбител'),
        ),
    ]
