# Generated by Django 3.2.25 on 2024-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240330_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Пълно име'),
        ),
    ]
