# Generated by Django 3.2.25 on 2024-03-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_clients_name_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user_id', to=settings.AUTH_USER_MODEL, verbose_name='id на потрeбител'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_user_id', to=settings.AUTH_USER_MODEL, verbose_name='id на потрeбител'),
        ),
    ]
