# Generated by Django 3.2.25 on 2024-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240330_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='action',
        ),
        migrations.AddField(
            model_name='log',
            name='client_id',
            field=models.IntegerField(default=0, verbose_name='id на клиента'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='', max_length=10, verbose_name='текущо състояние'),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='тема'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='име на потребител'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(default='', max_length=10, verbose_name='текущо действие'),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.IntegerField(default=0, verbose_name='id на заявка'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='id на потрeбител'),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
